services:
  yolov5-dev:
    image: yolov5:v1.0
    container_name: yolo
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./yolov5:/workspace/yolov5
      - ./model:/workspace/model
      - ./yolo_dataset:/workspace/yolo_dataset
    working_dir: /workspace
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
